Repository D0ryeon/Breaking_CyberPsycho, pull requests merged in 2023-09, with the labels that each got.

#9 #4 feature/game manager
  Assets/Scripts/Managers/GameManager.cs
Labels: feature

#14 fix/MainScene 메인씬 컨플릭트 문제 롤백
  Assets/Scenes/MainScene.unity
Labels: bug

#20 feature/ResourceManager
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/ResourceManager.cs
Labels: feature

#27 ### fix : SceneManager -> ScenesManager 이름 변경 / GameManager 수정
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/ScenesManager.cs
  Assets/Scripts/Managers/ScenesManager.cs.meta
Labels: bug

#32 feature/ScoreManager#17
  .gitignore
  Assets/Scripts/DataFormat.meta
  Assets/Scripts/DataFormat/Score.cs
  Assets/Scripts/DataFormat/Score.cs.meta
  Assets/Scripts/Managers/ScoreManager.cs
  Assets/Scripts/Utils/FileIO.cs
  Packages/manifest.json
  Packages/packages-lock.json
  app.config
Labels: feature

#33 #23/feature/scene manager+UI
  Assets/Resources/Prefabs/UI.meta
  Assets/Resources/Prefabs/UI/Main.meta
  Assets/Resources/Prefabs/UI/Main/ALLMainUI.prefab
  Assets/Resources/Prefabs/UI/Main/ALLMainUI.prefab.meta
  Assets/Resources/Prefabs/UI/Main/GameOverPopUP.prefab
  Assets/Resources/Prefabs/UI/Main/GameOverPopUP.prefab.meta
  Assets/Resources/Prefabs/UI/Main/TopBar.prefab
  Assets/Resources/Prefabs/UI/Main/TopBar.prefab.meta
  Assets/Resources/Prefabs/UI/Start.meta
  Assets/Resources/Prefabs/UI/Start/ALLStartUI.prefab
  Assets/Resources/Prefabs/UI/Start/ALLStartUI.prefab.meta
  Assets/Resources/Prefabs/UI/Start/OptionPopUP.prefab
  Assets/Resources/Prefabs/UI/Start/OptionPopUP.prefab.meta
  Assets/Resources/Prefabs/UI/Start/ScorePopUP.prefab
  Assets/Resources/Prefabs/UI/Start/ScorePopUP.prefab.meta
  Assets/Resources/Prefabs/UI/Start/Start.prefab
  Assets/Resources/Prefabs/UI/Start/Start.prefab.meta
  Assets/Scripts/Controllers/UIController.cs
  Assets/Scripts/Managers/ScenesManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#59 Feat/UIManager
  Assets/Data/PlayerScore.json
  Assets/Resources/Asset/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  Assets/Resources/Prefabs/UI/Popup.meta
  Assets/Resources/Prefabs/UI/Popup/Option.prefab
  Assets/Resources/Prefabs/UI/Popup/Option.prefab.meta
  Assets/Resources/Prefabs/UI/Popup/Score.prefab
  Assets/Resources/Prefabs/UI/Popup/Score.prefab.meta
  Assets/Resources/Prefabs/UI/Start/ALLStartUI.prefab
  Assets/Scenes/StartScene.unity
  Assets/Scripts/Controllers/UIController.cs
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/UIManager.cs
  Assets/Scripts/Managers/UIManager.cs.meta
  Assets/Scripts/UI.meta
  Assets/Scripts/UI/Popup.meta
  Assets/Scripts/UI/Popup/UI_Option.cs
  Assets/Scripts/UI/Popup/UI_Option.cs.meta
  Assets/Scripts/UI/Popup/UI_Popup.cs
  Assets/Scripts/UI/Popup/UI_Popup.cs.meta
  Assets/Scripts/UI/Popup/UI_Score.cs
  Assets/Scripts/UI/Popup/UI_Score.cs.meta
  Assets/Scripts/UI/Scene.meta
  Assets/Scripts/UI/UI_Base.cs
  Assets/Scripts/UI/UI_Base.cs.meta
  Assets/Scripts/UI/UI_Button.cs
  Assets/Scripts/UI/UI_Button.cs.meta
  Assets/Scripts/UI/UI_EventHandler.cs
  Assets/Scripts/UI/UI_EventHandler.cs.meta
  Assets/Scripts/Utils/Define.cs
  Assets/Scripts/Utils/Extension.cs
  Assets/Scripts/Utils/Extension.cs.meta
  Assets/Scripts/Utils/FileIO.cs
  Assets/Scripts/Utils/Util.cs
  Assets/Scripts/Utils/Util.cs.meta
Labels: feature

#61 feature/ScorePopupUI
  Assets/Data/PlayerScore.json
  Assets/Resources/Prefabs/UI/Popup/Score.prefab
  Assets/Scripts/DataFormat/Score.cs
  Assets/Scripts/Managers/ScoreManager.cs
  Assets/Scripts/Managers/StageManager.cs
  Assets/Scripts/UI/Popup/UI_Score.cs
  Assets/Scripts/UI/UI_Base.cs
Labels: feature

#75 feature/ItemManager
  .gitignore
  Assets/Data/PlayerScore.json
  Assets/Resources/Data.meta
  Assets/Resources/Data/ItemData.json
  Assets/Resources/Data/ItemData.json.meta
  Assets/Resources/Data/PlayerScore.json.meta
  Assets/Scripts/DataFormat/Item.cs
  Assets/Scripts/DataFormat/Item.cs.meta
  Assets/Scripts/Managers/DataManager.cs
  Assets/Scripts/Managers/ItemManager.cs
  Assets/Scripts/Utils/Define.cs
  Assets/Scripts/Utils/FileIO.cs
Labels: feature

#81 docs/리드미 초안 작성
  Assets/Resources/Data/PlayerScore.json.meta
Labels: documentation

#82 Docs/readme2
  .gitignore
  README.md
Labels: documentation

#86 fix/ScoreManager
  Assets/Scripts/Managers/ScoreManager.cs
  Assets/Scripts/UI/Popup/UI_Score.cs
Labels: bug

#87 Readme 시연 영상 추가
  README.md
Labels: documentation
